name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./Github_Actions/mea-itaas/github-service/gradlew

    - name: Build the project
      run: ./gradlew build
      working-directory: ./Github_Actions/mea-itaas/github-service


    - name: List build directory contents
      run: ls -al ./Github_Actions/mea-itaas/github-service/build/libs

    - name: Copy JAR to target directory
      run: cp ./Github_Actions/mea-itaas/github-service/build/libs/feedback-service-0.1.0.jar /home/tricon/helloSignUpgradedJars
